---
## MARIADB IN CENTOS ##

  - name: Install mariadb package (Centos)
    tags: centos,db,mariadb
    yum:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "CentOS"

  - name: "Mariadb - Restarting/Enabling on CentOS"
    service:
      name: mariadb
      state: restarted
      enabled: yes
    when: ansible_distribution == "CentOS"

